const AWAITING_CONFIRM = "AWAITING_CONFIRM";
const AWAITING_FULFILLMENT = "AWAITING_FULFILLMENT";
const DELIVERING = "DELIVERING";
const DELIVERED = "DELIVERED";
const CANCELED = "CANCELED";
const RETURNED = "RETURNED";

const ORDER_STATUSES = [
  AWAITING_CONFIRM,
  AWAITING_FULFILLMENT,
  DELIVERING,
  DELIVERED,
  CANCELED,
  RETURNED,
];

const ORDER_STATUS_ID_MAPPING = {
  ALL: 0,
  AWAITING_CONFIRM: 1,
  AWAITING_FULFILLMENT: 2,
  DELIVERING: 3,
  DELIVERED: 4,
  CANCELED: 5,
  RETURNED: 6,
};

module.exports = {
  AWAITING_CONFIRM,
  AWAITING_FULFILLMENT,
  DELIVERING,
  DELIVERED,
  CANCELED,
  RETURNED,
  ORDER_STATUSES,
  ORDER_STATUS_ID_MAPPING,
};
