const PRODUCT_NEWEST = "Newest";
const PRODUCT_TRENDING = "Trending";
const PRODUCT_FOR_YOU = "ForYou";
const PRODUCT_ALL = "All";
const PRODUCT_SALES = "Sales";

const PRODUCT_QUERY_TYPES = [
  PRODUCT_NEWEST,
  PRODUCT_TRENDING,
  PRODUCT_FOR_YOU,
  PRODUCT_ALL,
  PRODUCT_SALES,
];

module.exports = {
  PRODUCT_NEWEST,
  PRODUCT_TRENDING,
  PRODUCT_FOR_YOU,
  PRODUCT_ALL,
  PRODUCT_QUERY_TYPES,
  PRODUCT_SALES,
};
